In [12]:
# Import required libraries
import pandas as pd

In [11]:
!wget https://raw.githubusercontent.com/rebekz/datascience_course/main/data/housing/housing.csv
df = pd.read_csv('housing.csv')
display(df)

--2024-09-08 06:27:50--  https://raw.githubusercontent.com/rebekz/datascience_course/main/data/housing/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv.1’

housing.csv.1       100%[===================>]   1.36M  --.-KB/s    in 0.07s

2024-09-08 06:27:50 (20.7 MB/s) - ‘housing.csv.1’ saved [1423529/1423529]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [5]:
# Check NaN values in `total_bedrooms` column
df['total_bedrooms'].isnull().sum()

207

In [8]:
# Get median values in `total_bedrooms`
median_total_bedrooms = df['total_bedrooms'].median()
median_total_bedrooms

435.0

In [10]:
# Data Transformation (Filling NaN values with median)
df['total_bedrooms'].fillna(median_total_bedrooms)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64